// Sample recipe data for development seeding
// All amounts stored in canonical imperial units (fl oz, oz, °F)

import { RecipeDifficulty } from "@/lib/types";

export const seedRecipes = [
  {
    id: "recipe-spaghetti-carbonara",
    slug: "classic-spaghetti-carbonara",
    userId: "test-user-1",
    title: "Classic Spaghetti Carbonara",
    description:
      "A traditional Italian pasta dish made with eggs, cheese, pancetta, and black pepper. Rich, creamy, and absolutely delicious.",
    servings: 4,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: RecipeDifficulty.MEDIUM,
    cuisine: "Italian",
    sourceUrl: null,
    sourceName: null,
    isPublic: true,
    isArchived: false,
    ingredients: [
      {
        id: "ing-carbonara-1",
        name: "Spaghetti",
        amount: "16",
        unit: "oz",
        notes: "",
        groupName: null,
        sortOrder: 1,
        isOptional: false,
      },
      {
        id: "ing-carbonara-2",
        name: "Pancetta",
        amount: "6",
        unit: "oz",
        notes: "diced",
        groupName: null,
        sortOrder: 2,
        isOptional: false,
      },
      {
        id: "ing-carbonara-3",
        name: "Large eggs",
        amount: "4",
        unit: "whole",
        notes: "room temperature",
        groupName: null,
        sortOrder: 3,
        isOptional: false,
      },
      {
        id: "ing-carbonara-4",
        name: "Parmesan cheese",
        amount: "8",
        unit: "fl oz",
        notes: "freshly grated",
        groupName: null,
        sortOrder: 4,
        isOptional: false,
      },
      {
        id: "ing-carbonara-5",
        name: "Black pepper",
        amount: "0.17",
        unit: "fl oz",
        notes: "freshly ground",
        groupName: null,
        sortOrder: 5,
        isOptional: false,
      },
      {
        id: "ing-carbonara-6",
        name: "Salt",
        amount: "to taste",
        unit: "",
        notes: "for pasta water",
        groupName: null,
        sortOrder: 6,
        isOptional: false,
      },
    ],
    instructions: [
      {
        id: "inst-carbonara-1",
        stepNumber: 1,
        instruction:
          "Bring a large pot of salted water to boil. Cook spaghetti according to package directions until al dente.",
        timeMinutes: 10,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-carbonara-2",
        stepNumber: 2,
        instruction:
          "Meanwhile, cook pancetta in a large skillet over medium heat until crispy, about 5-7 minutes.",
        timeMinutes: 7,
        temperature: "medium heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-carbonara-3",
        stepNumber: 3,
        instruction:
          "In a bowl, whisk together eggs, Parmesan cheese, and black pepper until well combined.",
        timeMinutes: 2,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-carbonara-4",
        stepNumber: 4,
        instruction:
          "Reserve 1 cup pasta water, then drain spaghetti. Add hot pasta to the skillet with pancetta.",
        timeMinutes: 1,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-carbonara-5",
        stepNumber: 5,
        instruction:
          "Remove skillet from heat. Quickly toss pasta with egg mixture, adding pasta water as needed to create a creamy sauce.",
        timeMinutes: 2,
        temperature: null,
        notes: "Work quickly to prevent eggs from scrambling",
        groupName: null,
      },
      {
        id: "inst-carbonara-6",
        stepNumber: 6,
        instruction:
          "Serve immediately with additional Parmesan and black pepper.",
        timeMinutes: null,
        temperature: null,
        notes: null,
        groupName: null,
      },
    ],
    tags: ["tag-italian", "tag-main-course", "tag-dinner", "tag-quick"],
  },

  {
    id: "recipe-chicken-tacos",
    slug: "cilantro-lime-chicken-tacos",
    userId: "test-user-1",
    title: "Cilantro Lime Chicken Tacos",
    description:
      "Juicy grilled chicken marinated in lime and cilantro, served in warm tortillas with fresh toppings. Perfect for weeknight dinners or casual entertaining.",
    servings: 6,
    prepTimeMinutes: 20,
    cookTimeMinutes: 12,
    difficulty: RecipeDifficulty.EASY,
    cuisine: "Mexican",
    sourceUrl: null,
    sourceName: null,
    isPublic: true,
    isArchived: false,
    ingredients: [
      {
        id: "ing-tacos-1",
        name: "Chicken breasts",
        amount: "32",
        unit: "oz",
        notes: "boneless, skinless",
        groupName: "Chicken",
        sortOrder: 1,
        isOptional: false,
      },
      {
        id: "ing-tacos-2",
        name: "Lime juice",
        amount: "2",
        unit: "fl oz",
        notes: "freshly squeezed",
        groupName: "Chicken",
        sortOrder: 2,
        isOptional: false,
      },
      {
        id: "ing-tacos-3",
        name: "Olive oil",
        amount: "1",
        unit: "fl oz",
        notes: "",
        groupName: "Chicken",
        sortOrder: 3,
        isOptional: false,
      },
      {
        id: "ing-tacos-4",
        name: "Fresh cilantro",
        amount: "2",
        unit: "fl oz",
        notes: "chopped",
        groupName: "Chicken",
        sortOrder: 4,
        isOptional: false,
      },
      {
        id: "ing-tacos-5",
        name: "Cumin",
        amount: "0.17",
        unit: "fl oz",
        notes: "",
        groupName: "Chicken",
        sortOrder: 5,
        isOptional: false,
      },
      {
        id: "ing-tacos-6",
        name: "Chili powder",
        amount: "0.17",
        unit: "fl oz",
        notes: "",
        groupName: "Chicken",
        sortOrder: 6,
        isOptional: false,
      },
      {
        id: "ing-tacos-7",
        name: "Salt and pepper",
        amount: "to taste",
        unit: "",
        notes: "",
        groupName: "Chicken",
        sortOrder: 7,
        isOptional: false,
      },
      {
        id: "ing-tacos-8",
        name: "Corn tortillas",
        amount: "12",
        unit: "small",
        notes: "",
        groupName: "Assembly",
        sortOrder: 8,
        isOptional: false,
      },
      {
        id: "ing-tacos-9",
        name: "Red onion",
        amount: "1/2",
        unit: "medium",
        notes: "diced",
        groupName: "Toppings",
        sortOrder: 9,
        isOptional: true,
      },
      {
        id: "ing-tacos-10",
        name: "Avocado",
        amount: "2",
        unit: "medium",
        notes: "sliced",
        groupName: "Toppings",
        sortOrder: 10,
        isOptional: true,
      },
      {
        id: "ing-tacos-11",
        name: "Cotija cheese",
        amount: "4",
        unit: "fl oz",
        notes: "crumbled",
        groupName: "Toppings",
        sortOrder: 11,
        isOptional: true,
      },
      {
        id: "ing-tacos-12",
        name: "Lime wedges",
        amount: "for serving",
        unit: "",
        notes: "",
        groupName: "Toppings",
        sortOrder: 12,
        isOptional: true,
      },
    ],
    instructions: [
      {
        id: "inst-tacos-1",
        stepNumber: 1,
        instruction:
          "In a bowl, combine lime juice, olive oil, cilantro, cumin, chili powder, salt, and pepper to make marinade.",
        timeMinutes: 3,
        temperature: null,
        notes: null,
        groupName: "Preparation",
      },
      {
        id: "inst-tacos-2",
        stepNumber: 2,
        instruction:
          "Add chicken breasts to marinade and let sit for at least 15 minutes, or up to 2 hours in refrigerator.",
        timeMinutes: 15,
        temperature: null,
        notes: "Longer marination = more flavor",
        groupName: "Preparation",
      },
      {
        id: "inst-tacos-3",
        stepNumber: 3,
        instruction: "Preheat grill or grill pan to medium-high heat.",
        timeMinutes: 5,
        temperature: "medium-high heat",
        notes: null,
        groupName: "Cooking",
      },
      {
        id: "inst-tacos-4",
        stepNumber: 4,
        instruction:
          "Grill chicken for 6-7 minutes per side, or until internal temperature reaches 165°F.",
        timeMinutes: 14,
        temperature: "165°F internal",
        notes: null,
        groupName: "Cooking",
      },
      {
        id: "inst-tacos-5",
        stepNumber: 5,
        instruction: "Let chicken rest for 5 minutes, then slice into strips.",
        timeMinutes: 5,
        temperature: null,
        notes: null,
        groupName: "Cooking",
      },
      {
        id: "inst-tacos-6",
        stepNumber: 6,
        instruction:
          "Warm tortillas on the grill or in a dry skillet for 30 seconds per side.",
        timeMinutes: 2,
        temperature: null,
        notes: null,
        groupName: "Assembly",
      },
      {
        id: "inst-tacos-7",
        stepNumber: 7,
        instruction:
          "Assemble tacos with chicken and desired toppings. Serve with lime wedges.",
        timeMinutes: null,
        temperature: null,
        notes: null,
        groupName: "Assembly",
      },
    ],
    tags: [
      "tag-mexican",
      "tag-main-course",
      "tag-dinner",
      "tag-grilled",
      "tag-quick",
    ],
  },

  {
    id: "recipe-chocolate-chip-cookies",
    slug: "perfect-chocolate-chip-cookies",
    userId: "test-user-2",
    title: "Perfect Chocolate Chip Cookies",
    description:
      "The ultimate chocolate chip cookie recipe with crispy edges and chewy centers. Made with brown butter for extra depth of flavor.",
    servings: 24,
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    difficulty: RecipeDifficulty.EASY,
    cuisine: "American",
    sourceUrl: null,
    sourceName: null,
    isPublic: true,
    isArchived: false,
    ingredients: [
      {
        id: "ing-cookies-1",
        name: "Butter",
        amount: "1",
        unit: "cup",
        notes: "unsalted, room temperature",
        groupName: null,
        sortOrder: 1,
        isOptional: false,
      },
      {
        id: "ing-cookies-2",
        name: "Brown sugar",
        amount: "3/4",
        unit: "cup",
        notes: "packed",
        groupName: null,
        sortOrder: 2,
        isOptional: false,
      },
      {
        id: "ing-cookies-3",
        name: "Granulated sugar",
        amount: "2",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 3,
        isOptional: false,
      },
      {
        id: "ing-cookies-4",
        name: "Large eggs",
        amount: "2",
        unit: "whole",
        notes: "room temperature",
        groupName: null,
        sortOrder: 4,
        isOptional: false,
      },
      {
        id: "ing-cookies-5",
        name: "Vanilla extract",
        amount: "0.33",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 5,
        isOptional: false,
      },
      {
        id: "ing-cookies-6",
        name: "All-purpose flour",
        amount: "18",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 6,
        isOptional: false,
      },
      {
        id: "ing-cookies-7",
        name: "Baking soda",
        amount: "0.17",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 7,
        isOptional: false,
      },
      {
        id: "ing-cookies-8",
        name: "Salt",
        amount: "0.17",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 8,
        isOptional: false,
      },
      {
        id: "ing-cookies-9",
        name: "Chocolate chips",
        amount: "16",
        unit: "fl oz",
        notes: "semi-sweet",
        groupName: null,
        sortOrder: 9,
        isOptional: false,
      },
    ],
    instructions: [
      {
        id: "inst-cookies-1",
        stepNumber: 1,
        instruction:
          "Preheat oven to 375°F. Line baking sheets with parchment paper.",
        timeMinutes: 5,
        temperature: "375°F",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-2",
        stepNumber: 2,
        instruction:
          "Cream butter and both sugars until light and fluffy, about 3-4 minutes.",
        timeMinutes: 4,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-3",
        stepNumber: 3,
        instruction: "Beat in eggs one at a time, then add vanilla extract.",
        timeMinutes: 2,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-4",
        stepNumber: 4,
        instruction:
          "In a separate bowl, whisk together flour, baking soda, and salt.",
        timeMinutes: 1,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-5",
        stepNumber: 5,
        instruction:
          "Gradually mix dry ingredients into wet ingredients until just combined. Fold in chocolate chips.",
        timeMinutes: 2,
        temperature: null,
        notes: "Don't overmix",
        groupName: null,
      },
      {
        id: "inst-cookies-6",
        stepNumber: 6,
        instruction:
          "Drop rounded tablespoons of dough onto prepared baking sheets, 2 inches apart.",
        timeMinutes: 3,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-7",
        stepNumber: 7,
        instruction:
          "Bake for 9-11 minutes until golden brown around edges. Centers should still look slightly underbaked.",
        timeMinutes: 10,
        temperature: "375°F",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-cookies-8",
        stepNumber: 8,
        instruction:
          "Cool on baking sheet for 5 minutes, then transfer to wire rack to cool completely.",
        timeMinutes: 5,
        temperature: null,
        notes: null,
        groupName: null,
      },
    ],
    tags: ["tag-american", "tag-dessert", "tag-baked", "tag-comfort-food"],
  },

  {
    id: "recipe-quinoa-salad",
    slug: "mediterranean-quinoa-salad",
    userId: "test-user-2",
    title: "Mediterranean Quinoa Salad",
    description:
      "A fresh and healthy quinoa salad packed with Mediterranean flavors. Perfect as a light lunch or side dish.",
    servings: 6,
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: RecipeDifficulty.EASY,
    cuisine: "Mediterranean",
    sourceUrl: null,
    sourceName: null,
    isPublic: true,
    isArchived: false,
    ingredients: [
      {
        id: "ing-quinoa-1",
        name: "Quinoa",
        amount: "12",
        unit: "fl oz",
        notes: "rinsed",
        groupName: null,
        sortOrder: 1,
        isOptional: false,
      },
      {
        id: "ing-quinoa-2",
        name: "Water",
        amount: "24",
        unit: "fl oz",
        notes: "",
        groupName: null,
        sortOrder: 2,
        isOptional: false,
      },
      {
        id: "ing-quinoa-3",
        name: "Cherry tomatoes",
        amount: "16",
        unit: "fl oz",
        notes: "halved",
        groupName: null,
        sortOrder: 3,
        isOptional: false,
      },
      {
        id: "ing-quinoa-4",
        name: "Cucumber",
        amount: "1",
        unit: "large",
        notes: "diced",
        groupName: null,
        sortOrder: 4,
        isOptional: false,
      },
      {
        id: "ing-quinoa-5",
        name: "Red onion",
        amount: "1/2",
        unit: "medium",
        notes: "finely diced",
        groupName: null,
        sortOrder: 5,
        isOptional: false,
      },
      {
        id: "ing-quinoa-6",
        name: "Feta cheese",
        amount: "1",
        unit: "cup",
        notes: "crumbled",
        groupName: null,
        sortOrder: 6,
        isOptional: false,
      },
      {
        id: "ing-quinoa-7",
        name: "Kalamata olives",
        amount: "1/2",
        unit: "cup",
        notes: "pitted and halved",
        groupName: null,
        sortOrder: 7,
        isOptional: false,
      },
      {
        id: "ing-quinoa-8",
        name: "Fresh parsley",
        amount: "1/4",
        unit: "cup",
        notes: "chopped",
        groupName: null,
        sortOrder: 8,
        isOptional: false,
      },
      {
        id: "ing-quinoa-9",
        name: "Olive oil",
        amount: "1/3",
        unit: "cup",
        notes: "extra virgin",
        groupName: "Dressing",
        sortOrder: 9,
        isOptional: false,
      },
      {
        id: "ing-quinoa-10",
        name: "Lemon juice",
        amount: "1/4",
        unit: "cup",
        notes: "freshly squeezed",
        groupName: "Dressing",
        sortOrder: 10,
        isOptional: false,
      },
      {
        id: "ing-quinoa-11",
        name: "Garlic",
        amount: "2",
        unit: "cloves",
        notes: "minced",
        groupName: "Dressing",
        sortOrder: 11,
        isOptional: false,
      },
      {
        id: "ing-quinoa-12",
        name: "Dried oregano",
        amount: "1",
        unit: "tsp",
        notes: "",
        groupName: "Dressing",
        sortOrder: 12,
        isOptional: false,
      },
      {
        id: "ing-quinoa-13",
        name: "Salt and pepper",
        amount: "to taste",
        unit: "",
        notes: "",
        groupName: "Dressing",
        sortOrder: 13,
        isOptional: false,
      },
    ],
    instructions: [
      {
        id: "inst-quinoa-1",
        stepNumber: 1,
        instruction:
          "Bring water to a boil in a medium saucepan. Add quinoa, reduce heat to low, cover and simmer for 15 minutes.",
        timeMinutes: 15,
        temperature: "low heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-2",
        stepNumber: 2,
        instruction:
          "Remove from heat and let stand 5 minutes. Fluff with a fork and let cool completely.",
        timeMinutes: 20,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-3",
        stepNumber: 3,
        instruction:
          "Meanwhile, prepare vegetables: halve cherry tomatoes, dice cucumber, and finely dice red onion.",
        timeMinutes: 10,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-4",
        stepNumber: 4,
        instruction:
          "Make dressing by whisking together olive oil, lemon juice, garlic, oregano, salt, and pepper.",
        timeMinutes: 3,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-5",
        stepNumber: 5,
        instruction:
          "In a large bowl, combine cooled quinoa, tomatoes, cucumber, red onion, feta, olives, and parsley.",
        timeMinutes: 5,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-6",
        stepNumber: 6,
        instruction:
          "Pour dressing over salad and toss to combine. Taste and adjust seasoning as needed.",
        timeMinutes: 2,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-quinoa-7",
        stepNumber: 7,
        instruction:
          "Let salad sit for at least 30 minutes before serving to allow flavors to meld. Serve chilled or at room temperature.",
        timeMinutes: 30,
        temperature: null,
        notes: "Can be made up to 2 days ahead",
        groupName: null,
      },
    ],
    tags: [
      "tag-mediterranean",
      "tag-vegetarian",
      "tag-side-dish",
      "tag-no-cook",
      "tag-make-ahead",
    ],
  },

  {
    id: "recipe-beef-stir-fry",
    slug: "asian-beef-and-vegetable-stir-fry",
    userId: "test-user-3",
    title: "Asian Beef and Vegetable Stir Fry",
    description:
      "Quick and flavorful beef stir fry with crisp vegetables in a savory sauce. Perfect weeknight dinner served over rice.",
    servings: 4,
    prepTimeMinutes: 15,
    cookTimeMinutes: 8,
    difficulty: RecipeDifficulty.EASY,
    cuisine: "Asian",
    sourceUrl: null,
    sourceName: null,
    isPublic: false,
    isArchived: false,
    ingredients: [
      {
        id: "ing-stirfry-1",
        name: "Beef sirloin",
        amount: "1",
        unit: "lb",
        notes: "sliced thin against the grain",
        groupName: null,
        sortOrder: 1,
        isOptional: false,
      },
      {
        id: "ing-stirfry-2",
        name: "Broccoli",
        amount: "3",
        unit: "cups",
        notes: "cut into florets",
        groupName: null,
        sortOrder: 2,
        isOptional: false,
      },
      {
        id: "ing-stirfry-3",
        name: "Bell pepper",
        amount: "1",
        unit: "large",
        notes: "sliced",
        groupName: null,
        sortOrder: 3,
        isOptional: false,
      },
      {
        id: "ing-stirfry-4",
        name: "Carrots",
        amount: "2",
        unit: "medium",
        notes: "julienned",
        groupName: null,
        sortOrder: 4,
        isOptional: false,
      },
      {
        id: "ing-stirfry-5",
        name: "Snow peas",
        amount: "1",
        unit: "cup",
        notes: "trimmed",
        groupName: null,
        sortOrder: 5,
        isOptional: false,
      },
      {
        id: "ing-stirfry-6",
        name: "Green onions",
        amount: "3",
        unit: "stalks",
        notes: "sliced",
        groupName: null,
        sortOrder: 6,
        isOptional: false,
      },
      {
        id: "ing-stirfry-7",
        name: "Garlic",
        amount: "3",
        unit: "cloves",
        notes: "minced",
        groupName: null,
        sortOrder: 7,
        isOptional: false,
      },
      {
        id: "ing-stirfry-8",
        name: "Fresh ginger",
        amount: "1",
        unit: "tbsp",
        notes: "minced",
        groupName: null,
        sortOrder: 8,
        isOptional: false,
      },
      {
        id: "ing-stirfry-9",
        name: "Vegetable oil",
        amount: "2",
        unit: "tbsp",
        notes: "for cooking",
        groupName: null,
        sortOrder: 9,
        isOptional: false,
      },
      {
        id: "ing-stirfry-10",
        name: "Soy sauce",
        amount: "1/4",
        unit: "cup",
        notes: "",
        groupName: "Sauce",
        sortOrder: 10,
        isOptional: false,
      },
      {
        id: "ing-stirfry-11",
        name: "Oyster sauce",
        amount: "1",
        unit: "fl oz",
        notes: "",
        groupName: "Sauce",
        sortOrder: 11,
        isOptional: false,
      },
      {
        id: "ing-stirfry-12",
        name: "Cornstarch",
        amount: "0.5",
        unit: "fl oz",
        notes: "",
        groupName: "Sauce",
        sortOrder: 12,
        isOptional: false,
      },
      {
        id: "ing-stirfry-13",
        name: "Sesame oil",
        amount: "0.17",
        unit: "fl oz",
        notes: "",
        groupName: "Sauce",
        sortOrder: 13,
        isOptional: false,
      },
      {
        id: "ing-stirfry-14",
        name: "Water",
        amount: "1",
        unit: "fl oz",
        notes: "",
        groupName: "Sauce",
        sortOrder: 14,
        isOptional: false,
      },
    ],
    instructions: [
      {
        id: "inst-stirfry-1",
        stepNumber: 1,
        instruction:
          "Combine all sauce ingredients in a small bowl and whisk until smooth. Set aside.",
        timeMinutes: 2,
        temperature: null,
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-2",
        stepNumber: 2,
        instruction:
          "Heat 1 tablespoon oil in a large wok or skillet over high heat until smoking.",
        timeMinutes: 2,
        temperature: "high heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-3",
        stepNumber: 3,
        instruction:
          "Add beef and stir-fry until browned, about 2-3 minutes. Remove beef and set aside.",
        timeMinutes: 3,
        temperature: "high heat",
        notes: "Don't overcrowd the pan",
        groupName: null,
      },
      {
        id: "inst-stirfry-4",
        stepNumber: 4,
        instruction:
          "Add remaining oil to pan. Add broccoli and carrots, stir-fry for 2 minutes.",
        timeMinutes: 2,
        temperature: "high heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-5",
        stepNumber: 5,
        instruction:
          "Add bell pepper and snow peas, stir-fry for 1-2 minutes until vegetables are crisp-tender.",
        timeMinutes: 2,
        temperature: "high heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-6",
        stepNumber: 6,
        instruction:
          "Add garlic and ginger, stir-fry for 30 seconds until fragrant.",
        timeMinutes: 1,
        temperature: "high heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-7",
        stepNumber: 7,
        instruction:
          "Return beef to pan, add sauce, and toss everything together until well coated and sauce thickens, about 1 minute.",
        timeMinutes: 1,
        temperature: "high heat",
        notes: null,
        groupName: null,
      },
      {
        id: "inst-stirfry-8",
        stepNumber: 8,
        instruction:
          "Remove from heat, garnish with green onions, and serve immediately over rice.",
        timeMinutes: null,
        temperature: null,
        notes: null,
        groupName: null,
      },
    ],
    tags: ["tag-asian", "tag-main-course", "tag-dinner", "tag-quick"],
  },
];
