name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install ripgrep
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
          sudo dpkg -i ripgrep_13.0.0_amd64.deb

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type check
        run: pnpm run type-check

      - name: Run linter
        run: pnpm run lint:check


      - name: Check for unused dependencies
        run: pnpm run unused-deps:ci

  test:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint-and-type-check, test]
    env:
      SKIP_ENV_VALIDATION: true
      DATABASE_URL: "file:/tmp/test.db"
      BETTER_AUTH_SECRET: "test-secret-at-least-32-chars-long"
      BETTER_AUTH_URL: "http://localhost:3000"
      OLLAMA_BASE_URL: "http://localhost:11434"
      ENCRYPTION_SECRET: "test-encryption-secret-must-be-exactly-64-chars-long-12345678901"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

  code-quality:
    runs-on: ubuntu-latest
    # This job runs independently and doesn't block other jobs
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install ripgrep
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
          sudo dpkg -i ripgrep_13.0.0_amd64.deb

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for unused code
        run: pnpm run unused-code:ci
        continue-on-error: true

      - name: Run comprehensive health checks
        run: pnpm run health-check:ci
        continue-on-error: true
